# Nombre del servicio
spring.application.name=banco-central-xyz

# Puerto del Backend Central
server.port=8081


# =========================================================
# BASE DE DATOS POSTGRESQL
# =========================================================

# PostgreSQL ejecutándose mediante Docker
spring.datasource.url=jdbc:postgresql://localhost:5433/banco_xyz

# Usuario definido en docker-compose.yml
spring.datasource.username=banco_admin

# La contraseña se obtiene desde una variable de entorno
# para evitar subir credenciales a GitHub.
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}


# =========================================================
# JPA / HIBERNATE
# =========================================================

# Crea o actualiza las tablas según las entidades Java.
# No elimina información existente.
spring.jpa.hibernate.ddl-auto=update

# Permite visualizar las consultas SQL mientras desarrollamos.
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true


# =========================================================
# INICIALIZACION SQL
# =========================================================

# Ejecuta schema-postgresql.sql al iniciar la aplicación.
spring.sql.init.mode=always

spring.sql.init.platform=postgresql


# =========================================================
# JWT
# =========================================================

# Mismo secreto utilizado por los tres BFF.
jwt.secret=${JWT_SECRET}