spring.application.name=banco-batch

# ===============================
# PostgreSQL
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/banco_batch
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

# ===============================
# Spring Batch
# ===============================
spring.batch.jdbc.initialize-schema=always
spring.batch.job.enabled=true
spring.batch.job.name=estadosAnualesJob

# ===============================
# Inicializacion SQL
# ===============================
spring.sql.init.mode=always

# ===============================
# Logs
# ===============================
logging.level.org.springframework.batch=INFO

# ===============================
# Reglas de negocio - Intereses
# ===============================
banco.interes.ahorro=0.01
banco.interes.prestamo=0.02

# ===============================
# Semana 3 - Optimizacion Batch
# ===============================
banco.batch.chunk-size=5
banco.batch.threads=3
banco.batch.queue-capacity=10
banco.batch.retry-limit=3
banco.batch.skip-limit=1000
banco.batch.backoff-ms=500