spring.application.name=banco-batch

# ===============================
# PostgreSQL
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/banco_batch
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

# ===============================
# Spring Batch
# ===============================
spring.batch.jdbc.initialize-schema=always
spring.batch.job.enabled=false

# ===============================
# Inicializacion SQL
# ===============================
spring.sql.init.mode=always

# ===============================
# Logs
# ===============================
logging.level.org.springframework.batch=INFO

# ===============================
# Reglas de negocio - Intereses
# ===============================
banco.interes.ahorro=0.01
banco.interes.prestamo=0.02
