spring.application.name=bff-web

server.port=8084

# Conexion con el Backend Central
banco.central.url=http://localhost:8081

# JWT compartido con el Backend Central
jwt.secret=${JWT_SECRET}

# Configuracion HTTPS
server.ssl.enabled=true
server.ssl.key-store=classpath:certs/bff-web.p12
server.ssl.key-store-type=PKCS12
server.ssl.key-store-password=${SSL_KEYSTORE_PASSWORD}
server.ssl.key-password=${SSL_KEYSTORE_PASSWORD}
server.ssl.key-alias=bff-web