# =========================================================
# APLICACION
# =========================================================

spring.application.name=bff-mobile

# Puerto exclusivo del BFF Mobile
server.port=8083


# =========================================================
# BACKEND CENTRAL
# =========================================================

# El BFF consulta internamente al Banco Central.
banco.central.url=http://localhost:8081


# =========================================================
# JWT
# =========================================================

# Debe ser el mismo secreto utilizado por Banco Central.
jwt.secret=${JWT_SECRET}


# =========================================================
# HTTPS
# =========================================================

server.ssl.enabled=true

server.ssl.key-store=classpath:certs/bff-mobile.p12

server.ssl.key-store-type=PKCS12

server.ssl.key-store-password=${SSL_KEYSTORE_PASSWORD}

server.ssl.key-password=${SSL_KEYSTORE_PASSWORD}

server.ssl.key-alias=bff-mobile