# =========================================================
# APLICACION
# =========================================================

spring.application.name=bff-cajeros

server.port=8082


# =========================================================
# BACKEND CENTRAL
# =========================================================

banco.central.url=http://localhost:8081


# =========================================================
# JWT
# =========================================================

jwt.secret=${JWT_SECRET}


# =========================================================
# HTTPS
# =========================================================

server.ssl.enabled=true

server.ssl.key-store=classpath:certs/bff-cajeros.p12

server.ssl.key-store-type=PKCS12

server.ssl.key-store-password=${SSL_KEYSTORE_PASSWORD}

server.ssl.key-password=${SSL_KEYSTORE_PASSWORD}

server.ssl.key-alias=bff-cajeros
