spring.application.name=banco-central-xyz
server.port=8081  

spring.datasource.url=jdbc:postgresql://ep-curly-salad-acqh1vb2.sa-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=${DB_PASSWORD}

spring.sql.init.mode=always
spring.sql.init.platform=postgresql

jwt.secret=${JWT_SECRET}